version: 0.0
os: linux
files:
  - source: /sample-app/
    destination: /web/
hooks:
  AfterInstall:
    - location: sample-app/scripts/mkdir.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: sample-app/scripts/start_flask.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: sample-app/scripts/stop_flask1.sh
      timeout: 300
      runas: root
